############################################################
# config 服务配置中心
# web访问端口号  约定：7080
############################################################
server:
  port: 7080
  tomcat:
    uri-encoding: UTF-8

############################################################
# 项目配置信息
############################################################
spring:
  application:
    name: spring-cloud-config
  cloud:
    ## 配置中心 远程的配置信息 Git 仓库
    config:
      server:
        git:
          uri: https://gitee.com/codeprobe/singularity-community-config.git
          default-label: main  # 解决错误404或者是No such label: master问题
          username: codeprobe         # 仓库若是私有 private 需要用户名和密码
          password: lionido778@gitee
  ## RabbitMQ
  rabbitmq:
    host: 192.168.80.3
    port: 5672
    username: admin
    password: lionido778
    virtual-host: singularity-community-dev

############################################################
# eureka client 配置信息
############################################################
eureka:
  server:
    hostname: eureka
    port: 7000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
      defaultZone: http://eureka-cluster-7001:7001/eureka/,http://eureka-cluster-7002:7002/eureka/,http://eureka-cluster-7003:7003/eureka/


  # 配置动态刷新git配置的路径终端请求地址  eg: http://{微服务ip}:{微服务port}/actuator/bus-refresh (批量无差别)
  #                                    http://{微服务ip}:{微服务port}/actuator/bus-refresh/{微服务实例ID}:{微服务Port} (精准打击)
management:
  endpoints:
    web:
      exposure:
        include: "*"