############################################################
# 文章 微服务
# web访问端口号  约定：8001
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

## 配置项目信息
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  main:
    allow-bean-definition-overriding: true  #允许同一个项目中多个接口使用 @FeignClient 调用同一个服务

## mybatis 配置
mybatis:
  type-aliases-package: cn.codeprobe.pojo         # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml        # mapper映射文件

## mybatis mapper 配置
# 通用 Mapper 配置
mapper:
  mappers: cn.codeprobe.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL

# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true


############################################################
# eureka client 配置信息
############################################################
eureka:
  # 自定义eureka server的信息
  server:
    hostname: eureka.codeprobe.cn
    port: 7000
  client:
    # 所有的微服务都必须注册到eureka中
    register-with-eureka: true
    # 从注册中心获得检索服务实例
    fetch-registry: true
    # 注册中心的服务地址
    service-url:
      #      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
      defaultZone: http://eureka-cluster-7001:7001/eureka/,http://eureka-cluster-7002:7002/eureka/,http://eureka-cluster-7003:7003/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3      # 调整微服务（eureka client）和注册中心（eureka server）的心跳时间
    lease-expiration-duration-in-seconds: 5   # eureka 举例最近的一次心跳等待提出的时间，默认90s

ribbon:
  ConnectTimeout: 5000          # 创建连接的超时时间，单位：ms
  ReadTimeout: 5000             # 在连接创建好以后，调用接口的超时时间，单位：ms
  MaxAutoRetries: 1             # 最大重试次数
  MaxAutoRetriesNextServer: 2   # 切换到下个微服务实例的重试次数
  # 当请求到某个微服务5s，超时后会进行重试，先重试连接自己当前的这个实例
  # 如果当前重试失败1次，则会切换到访问集群中的下一个微服务实例，切换最大为2次